FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt-get install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb \
    && apt-get clean

WORKDIR /usr/src/app

COPY scraper/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /usr/src/app/secret

COPY secret/gcp_credentials.json /usr/src/app/secret/gcp_credentials.json

ENV GOOGLE_APPLICATION_CREDENTIALS="/usr/src/app/secret/gcp_credentials.json"

COPY scraper/ .
