bootstrap.servers=dataeng-kafka:9092
listeners=http://0.0.0.0:8088
ksql.schema.registry.url=http://dataeng-schema-registry:8081
ksql.logging.processing.stream.auto.create=true
ksql.logging.processing.topic.auto.create=true